### ISSUE TITLE
Crashes frequently on elementary OS 5.1.7

### ISSUE THREAD

**Issue by Suzie97** [stsdc/monitor#227] opened 2021-04-06 08:39 UTC
The app crashes and becomes when the CPU temperature crosses about 65 degrees Celcius.

![Screenshot from 2021-04-06 14-08-39](https://user-images.githubusercontent.com/68198116/113683259-9fef4c00-96e1-11eb-815f-4394b18acf28.png)

**Comment by Suzie97** [comment] 2021-04-06 08:39
I haven't checked it out on my other laptop with a 6 core i7. Maybe its because my processor is too old.

**Comment by stsdc** [comment] 2021-04-06 14:06
Can You please run it with: `G_MESSAGES_DEBUG=all ./com.github.stsdc.monitor`? And provide some debug info?

**Comment by Suzie97** [comment] 2021-04-06 14:22
```
rajdeep@rajdeep-HP-1000 07:51:02 ~ →  G_MESSAGES_DEBUG=all com.github.stsdc.monitor
(com.github.stsdc.monitor:29756): Gtk-DEBUG: 19:51:12.596: Connecting to session manager
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:12.619: CPU.vala:51: Number of cores: 2
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:12.619: TemperatureSensor.vala:69: Found temp. sensor: BAT0
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:12.619: TemperatureSensor.vala:69: Found temp. sensor: AC
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:12.619: TemperatureSensor.vala:40: Found temp. sensor: coretemp
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:12.620: TemperatureSensor.vala:62: 54000
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:12.620: TemperatureSensor.vala:62: 54000
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:12.620: TemperatureSensor.vala:69: Found temp. sensor: acpitz
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:12.876: ProcessUtils.vala:5: sh
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:12.878: ProcessUtils.vala:5: sh
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:12.882: ProcessUtils.vala:5: sh
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:12.884: ProcessUtils.vala:5: sh
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:12.885: ProcessUtils.vala:5: sh
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:12.886: ProcessUtils.vala:5: sh
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:12.987: DBusServer.vala:38: DBus registered!
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.060: TreeViewModel.vala:34: add_running_processes
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.061: TreeViewModel.vala:43: Add process 2683 Parent PID: 1
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.064: TreeViewModel.vala:43: Add process 2684 Parent PID: 2683
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.064: TreeViewModel.vala:43: Add process 2700 Parent PID: 1
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.064: TreeViewModel.vala:43: Add process 2703 Parent PID: 2504
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.064: TreeViewModel.vala:43: Add process 2712 Parent PID: 2683
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.065: TreeViewModel.vala:43: Add process 2715 Parent PID: 2683
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.065: TreeViewModel.vala:43: Add process 2720 Parent PID: 2683
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.065: TreeViewModel.vala:43: Add process 2825 Parent PID: 2703
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.065: TreeViewModel.vala:43: Add process 2838 Parent PID: 2683
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.065: TreeViewModel.vala:43: Add process 2843 Parent PID: 2838
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.065: TreeViewModel.vala:43: Add process 2846 Parent PID: 2683
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.065: TreeViewModel.vala:43: Add process 2867 Parent PID: 2703
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.065: TreeViewModel.vala:43: Add process 2868 Parent PID: 2703
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.065: TreeViewModel.vala:43: Add process 2870 Parent PID: 2703
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.065: TreeViewModel.vala:43: Add process 2872 Parent PID: 2703
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.065: TreeViewModel.vala:43: Add process 2874 Parent PID: 2703
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.065: TreeViewModel.vala:43: Add process 2883 Parent PID: 2703
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.066: TreeViewModel.vala:43: Add process 2891 Parent PID: 2703
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.066: TreeViewModel.vala:43: Add process 2903 Parent PID: 2703
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.066: TreeViewModel.vala:43: Add process 2905 Parent PID: 2703
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.066: TreeViewModel.vala:43: Add process 2913 Parent PID: 2703
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.066: TreeViewModel.vala:43: Add process 2925 Parent PID: 2703
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.066: TreeViewModel.vala:43: Add process 2926 Parent PID: 1
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.066: TreeViewModel.vala:43: Add process 2935 Parent PID: 2703
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.066: TreeViewModel.vala:43: Add process 2938 Parent PID: 2703
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.066: TreeViewModel.vala:43: Add process 2940 Parent PID: 2703
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.066: TreeViewModel.vala:43: Add process 2942 Parent PID: 2703
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.066: TreeViewModel.vala:43: Add process 2945 Parent PID: 2703
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.066: TreeViewModel.vala:43: Add process 2960 Parent PID: 2683
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.067: TreeViewModel.vala:43: Add process 2978 Parent PID: 1
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.067: TreeViewModel.vala:43: Add process 3023 Parent PID: 2703
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.067: TreeViewModel.vala:43: Add process 3053 Parent PID: 2703
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.067: TreeViewModel.vala:43: Add process 3054 Parent PID: 2703
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.067: TreeViewModel.vala:43: Add process 3060 Parent PID: 2703
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.067: TreeViewModel.vala:43: Add process 3072 Parent PID: 2683
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.067: TreeViewModel.vala:43: Add process 3115 Parent PID: 2703
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.067: TreeViewModel.vala:43: Add process 3122 Parent PID: 2703
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.067: TreeViewModel.vala:43: Add process 3126 Parent PID: 2703
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.067: TreeViewModel.vala:43: Add process 3129 Parent PID: 2703
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.067: TreeViewModel.vala:43: Add process 3135 Parent PID: 2703
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.067: TreeViewModel.vala:43: Add process 3141 Parent PID: 2703
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.068: TreeViewModel.vala:43: Add process 3144 Parent PID: 2703
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.068: TreeViewModel.vala:43: Add process 3153 Parent PID: 2703
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.068: TreeViewModel.vala:43: Add process 3156 Parent PID: 2703
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.068: TreeViewModel.vala:43: Add process 3162 Parent PID: 2703
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.068: TreeViewModel.vala:43: Add process 3169 Parent PID: 2703
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.068: TreeViewModel.vala:43: Add process 3277 Parent PID: 2683
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.068: TreeViewModel.vala:43: Add process 3301 Parent PID: 2683
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.068: TreeViewModel.vala:43: Add process 3336 Parent PID: 3126
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.068: TreeViewModel.vala:43: Add process 3338 Parent PID: 3126
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.068: TreeViewModel.vala:43: Add process 3340 Parent PID: 3126
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.068: TreeViewModel.vala:43: Add process 3354 Parent PID: 3301
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.068: TreeViewModel.vala:43: Add process 3363 Parent PID: 3340
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.069: TreeViewModel.vala:43: Add process 3380 Parent PID: 3354
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.069: TreeViewModel.vala:43: Add process 3381 Parent PID: 3380
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.069: TreeViewModel.vala:43: Add process 3419 Parent PID: 2683
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.069: TreeViewModel.vala:43: Add process 3427 Parent PID: 3419
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.069: TreeViewModel.vala:43: Add process 3708 Parent PID: 2703
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.069: TreeViewModel.vala:43: Add process 3795 Parent PID: 3708
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.069: TreeViewModel.vala:43: Add process 3796 Parent PID: 3795
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.069: TreeViewModel.vala:43: Add process 3854 Parent PID: 2683
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.069: TreeViewModel.vala:43: Add process 3859 Parent PID: 2683
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.069: TreeViewModel.vala:43: Add process 3862 Parent PID: 2683
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.069: TreeViewModel.vala:43: Add process 3905 Parent PID: 2683
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.069: TreeViewModel.vala:43: Add process 3910 Parent PID: 2715
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.070: TreeViewModel.vala:43: Add process 3933 Parent PID: 2683
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.070: TreeViewModel.vala:43: Add process 3951 Parent PID: 2683
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.070: TreeViewModel.vala:43: Add process 3955 Parent PID: 2683
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.070: TreeViewModel.vala:43: Add process 3961 Parent PID: 2683
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.070: TreeViewModel.vala:43: Add process 3966 Parent PID: 2683
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.070: TreeViewModel.vala:43: Add process 4094 Parent PID: 2683
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.070: TreeViewModel.vala:43: Add process 4121 Parent PID: 2683
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.070: TreeViewModel.vala:43: Add process 4125 Parent PID: 2683
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.070: TreeViewModel.vala:43: Add process 4405 Parent PID: 2683
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.070: TreeViewModel.vala:43: Add process 4409 Parent PID: 2683
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.070: TreeViewModel.vala:43: Add process 4418 Parent PID: 4405
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.070: TreeViewModel.vala:43: Add process 4419 Parent PID: 4418
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.071: TreeViewModel.vala:43: Add process 15603 Parent PID: 2715
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.071: TreeViewModel.vala:43: Add process 16574 Parent PID: 1
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.071: TreeViewModel.vala:43: Add process 16588 Parent PID: 16574
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.071: TreeViewModel.vala:43: Add process 16589 Parent PID: 16588
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.071: TreeViewModel.vala:43: Add process 27710 Parent PID: 1
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.071: TreeViewModel.vala:43: Add process 27715 Parent PID: 27710
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.071: TreeViewModel.vala:43: Add process 28069 Parent PID: 1
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.071: TreeViewModel.vala:43: Add process 28081 Parent PID: 28069
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.071: TreeViewModel.vala:43: Add process 28128 Parent PID: 28069
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.071: TreeViewModel.vala:43: Add process 28129 Parent PID: 28128
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.071: TreeViewModel.vala:43: Add process 28297 Parent PID: 28081
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.071: TreeViewModel.vala:43: Add process 28298 Parent PID: 28297
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.072: TreeViewModel.vala:43: Add process 28388 Parent PID: 2715
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.072: TreeViewModel.vala:43: Add process 28456 Parent PID: 2715
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.072: TreeViewModel.vala:43: Add process 28827 Parent PID: 28069
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.072: TreeViewModel.vala:43: Add process 28887 Parent PID: 28069
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.072: TreeViewModel.vala:43: Add process 29262 Parent PID: 1
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.072: TreeViewModel.vala:43: Add process 29272 Parent PID: 29262
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:13.072: TreeViewModel.vala:43: Add process 29756 Parent PID: 29272
** (com.github.stsdc.monitor:29756): DEBUG: 19:51:47.742: TreeViewModel.vala:43: Add process 29954 Parent PID: 3023
```

**Comment by Suzie97** [comment] 2021-04-06 14:24
![Screenshot from 2021-04-06 19-51-38](https://user-images.githubusercontent.com/68198116/113726320-c0cf9580-9711-11eb-8086-93475f29fe57.png)


![Screenshot from 2021-04-06 19-51-59](https://user-images.githubusercontent.com/68198116/113726227-ac8b9880-9711-11eb-812f-0cd2c14940b1.png)

The app crashed when I was maximizing it.

**Comment by Suzie97** [comment] 2021-04-06 14:28
I changed the name of the issue because the app also crashes when CPU temp is low.

**Comment by stsdc** [comment] 2021-04-06 17:27
Thanks for filling an issue. This is a duplicate of #225

**Closed by stsdc** 2021-04-06 17:27 UTC
