### ISSUE TITLE
Status bar indicator breaks app.

### ISSUE THREAD

**Issue by Alterae** [stsdc/monitor#106] opened 2019-06-24 17:44 UTC
So, I made the mistake of turning on the status bar indicator.  Now I can't open the app itself.
Clicking the open or quit buttons in the status indicator's dropdown simply lags for a bit, and then does nothing.  Attempting to open Monitor from the app launcher causes the app icon to appear on the dock, but doesn't open the app.  Clicking on the icon now that it's on the dock simply causes it to bounce once, and then nothing.

**Comment by stsdc** [comment] 2019-06-24 19:31
I believe this is a duplicate of #88

**Closed by stsdc** 2019-06-24 19:31 UTC
