### ISSUE TITLE
The monitor app doesn't start at all.

### ISSUE THREAD

**Issue by ijiki16** [stsdc/monitor#205] opened 2020-09-02 17:15 UTC
when I try to open the app normally the app icon appears on the dock but after a few seconds, it disappears. From the terminal, I get this error "(com.github.stsdc.monitor:7287): GLib-GIO-CRITICAL **: 21:08:01.945: This application can not open files."

**Comment by stsdc** [comment] 2020-09-02 17:40
How did you install the app?
What is your system version?

Try to run with debug messages: `G_MESSAGES_DEBUG=all ./com.github.stsdc.monitor`

**Comment by ijiki16** [comment] 2020-09-02 19:00
1) AppCenter
2) elementary OS 5.1.7 Hera

debug output `(com.github.stsdc.monitor:8249): Gtk-DEBUG: 22:58:23.512: Connecting to session manager
** (com.github.stsdc.monitor:8249): DEBUG: 22:58:23.534: CPU.vala:51: Number of cores: 4
** (com.github.stsdc.monitor:8249): DEBUG: 22:58:23.534: TemperatureSensor.vala:37: Found temp. sensor: coretemp
** (com.github.stsdc.monitor:8249): DEBUG: 22:58:23.535: TemperatureSensor.vala:59: 42000
** (com.github.stsdc.monitor:8249): DEBUG: 22:58:23.535: TemperatureSensor.vala:59: 42000
** (com.github.stsdc.monitor:8249): DEBUG: 22:58:23.535: TemperatureSensor.vala:59: 42000
** (com.github.stsdc.monitor:8249): DEBUG: 22:58:23.536: TemperatureSensor.vala:59: 42000

** (com.github.stsdc.monitor:8249): ERROR **: 22:58:23.536: TemperatureSensor.vala:77: Failed to open file “/sys/class/hwmon/hwmon1/name”: No such file or directory
`

**Comment by stsdc** [comment] 2020-09-02 19:19
Duplicate of #204. Will be fixed in the next release.

**Closed by stsdc** 2020-09-02 19:19 UTC
