### ISSUE TITLE
High cpu usage

### ISSUE THREAD

**Issue by diegomagela** [stsdc/monitor#160] opened 2020-04-04 17:03 UTC
Always after 15-30 min the CPU usage blow up to 99%. Is this happening just with me?

**Comment by stsdc** [comment] 2020-04-04 20:22
Duplicate of #88. Welcome to the club :grimacing:. Working on fix.

**Closed by stsdc** 2020-04-04 20:22 UTC

**Comment by RaulBSantos** [comment] 2020-04-09 15:26
> Always after 15-30 min the CPU usage blow up to 99%. Is this happening just with me?

Same here.
