### ISSUE TITLE
Cant open app because of temperature sensor error

### ISSUE THREAD

**Issue by Hedronmx** [stsdc/monitor#206] opened 2020-09-05 11:04 UTC
When I try to open the app i get the following error
`
** (com.github.stsdc.monitor:28320): ERROR **: 04:02:10.282: TemperatureSensor.vala:77: Failed to open file “/sys/class/hwmon/hwmon2/name”: No such file or directory
`

**Comment by stsdc** [comment] 2020-09-05 19:55
Duplicate of #204

**Closed by stsdc** 2020-09-05 19:55 UTC
