### ISSUE TITLE
Handle exception when CPU temp cannot be read

### ISSUE THREAD

**Issue by stathis85** [stsdc/monitor#213] opened 2020-10-15 10:16 UTC
It seems that after the latest update the temperature indication for my CPU is not functional any more.
![Screenshot from 2020-10-15 12-57-39](https://user-images.githubusercontent.com/16205275/96110292-553a0780-0ee8-11eb-9ce7-48a847d17cc3.png)

And this is the indicator at the task bar.
![Screenshot from 2020-10-15 12-59-11](https://user-images.githubusercontent.com/16205275/96110294-566b3480-0ee8-11eb-9c2e-2c004bd071dd.png)

As you can see the CPU is an AMD Phenom II X6 1100T on a ASUS M4A89GTD PRO/USB3 mobo.

**Comment by stsdc** [comment] 2020-10-15 17:44
Hello, thanks for the report.

You'll have to debug this, because this is hardware specific issue.
Start Monitor with a  debug flag:  `G_MESSAGES_DEBUG=all ./com.github.stsdc.monitor`
The file with a temperature info is probably stored in different place. Try to look it up somewhere in here `/sys/class/hwmon/hwmon0`

**Comment by hikkijojo** [comment] 2021-05-21 03:58
Hello similarly, my AMD 5800x CPU Temp is empty.

**Comment by stsdc** [comment] 2021-05-21 19:37
Hello @hikkijojo !
What kernel are You using?

**Comment by hikkijojo** [comment] 2021-05-25 00:56
> Hello @hikkijojo !
> What kernel are You using?
HI @stsdc, elementary OS

**Comment by stsdc** [comment] 2021-05-25 08:56
I think You have to update kernel. Your CPU is too new and old kernel doesn't provide temperature info.

**Comment by hikkijojo** [comment] 2021-06-02 03:23
> I think You have to update kernel. Your CPU is too new and old kernel doesn't provide temperature info for newest CPUs.

Thank you. I appreciate it!!!!!!!!!

![0602](https://user-images.githubusercontent.com/14817041/120419376-eb963d00-c394-11eb-92a5-42941df7af75.png)

**Comment by camellan** [comment] 2021-11-09 10:10
I'm not sure if this is right because I don't know which sensor is responsible for the cpu temperature...
https://github.com/camellan/monitor/commit/c01826189219d8777d22643ced80e579282fb4fb

**Comment by camellan** [comment] 2021-11-09 10:11
![Снимок экрана от 2021-11-09 14-10-49](https://user-images.githubusercontent.com/7396198/140905199-793fd69f-d8f9-444b-9af9-a94b819f39df.png)

**Comment by stsdc** [comment] 2021-11-09 10:56
@camellan I'm in a process of rewriting parsing of hwmon. Could You please paste output of:
```bash
cat /sys/class/hwmon/hwmon*/name
```

**Comment by camellan** [comment] 2021-11-09 11:38
$ cat /sys/class/hwmon/hwmon*/name
fam15h_power
k10temp
$

**Comment by camellan** [comment] 2021-11-09 11:41
There is also this sensor:
$ cat /sys/class/hwmon/hwmon0/device/name
f71889ed
$

**Comment by stsdc** [comment] 2021-11-09 15:53
`k10temp` is the right sensor for AMD processors. 
Should be detected by: https://github.com/stsdc/monitor/blob/13720fb73ea2165a4b8fe837a53581d0d4a80b7f/src/Resources/TemperatureSensor.vala#L40

Check its `temp*_label`

**Comment by camellan** [comment] 2021-11-09 16:51
I'm sorry, I don't understand the command cat ./temp*_label

**Comment by camellan** [comment] 2021-11-09 16:56
With my processor this condition is not met
https://github.com/stsdc/monitor/blob/13720fb73ea2165a4b8fe837a53581d0d4a80b7f/src/Resources/TemperatureSensor.vala#L52

**Comment by stsdc** [comment] 2021-11-09 17:11
@camellan cd into directory where you have `name == k10temp` and run `cat ./temp*_label`

**Comment by camellan** [comment] 2021-11-09 17:53
camellan@LADOGA:~/git/monitor/build$ cd /sys/class/hwmon/hwmon2
camellan@LADOGA:/sys/class/hwmon/hwmon2$ cat ./temp*_label
cat: './temp*_label': Нет такого файла или каталога
camellan@LADOGA:/sys/class/hwmon/hwmon2$ ls
device  name  power  subsystem  temp1_crit  temp1_crit_hyst  temp1_input  temp1_max  uevent
camellan@LADOGA:/sys/class/hwmon/hwmon2$

**Comment by stsdc** [comment] 2021-11-09 18:27
Ok, I understand the cause. Will be fixed in the next release.

What kernel are you using?

**Comment by camellan** [comment] 2021-11-09 18:29
5.11.0-40-generic

**Comment by camellan** [comment] 2021-11-10 12:28
<<<>>>
** (com.github.stsdc.monitor:18376): CRITICAL **: 16:25:24.131: monitor_ihwmon_paths_parser_interface_real_open_file: assertion 'filename != NULL' failed
<<<>>>
** (com.github.stsdc.monitor:18376): DEBUG: 16:25:24.737: TreeViewModel.vala:43: Add process 16612 Parent PID: 16553
** (com.github.stsdc.monitor:18376): DEBUG: 16:25:24.737: TreeViewModel.vala:43: Add process 16638 Parent PID: 16581
** (com.github.stsdc.monitor:18376): DEBUG: 16:25:24.737: TreeViewModel.vala:43: Add process 16647 Parent PID: 16553
** (com.github.stsdc.monitor:18376): DEBUG: 16:25:24.737: TreeViewModel.vala:43: Add process 16668 Parent PID: 16553
** (com.github.stsdc.monitor:18376): DEBUG: 16:25:24.738: TreeViewModel.vala:43: Add process 16755 Parent PID: 16531
** (com.github.stsdc.monitor:18376): DEBUG: 16:25:24.738: TreeViewModel.vala:43: Add process 16862 Parent PID: 16553
** (com.github.stsdc.monitor:18376): DEBUG: 16:25:24.738: TreeViewModel.vala:43: Add process 16867 Parent PID: 16553
** (com.github.stsdc.monitor:18376): DEBUG: 16:25:24.738: TreeViewModel.vala:43: Add process 17247 Parent PID: 1
** (com.github.stsdc.monitor:18376): DEBUG: 16:25:24.738: TreeViewModel.vala:43: Add process 17268 Parent PID: 17247
** (com.github.stsdc.monitor:18376): DEBUG: 16:25:24.738: TreeViewModel.vala:43: Add process 17271 Parent PID: 17247
** (com.github.stsdc.monitor:18376): DEBUG: 16:25:24.738: TreeViewModel.vala:43: Add process 17969 Parent PID: 16553
** (com.github.stsdc.monitor:18376): DEBUG: 16:25:24.738: TreeViewModel.vala:43: Add process 18122 Parent PID: 15106
** (com.github.stsdc.monitor:18376): DEBUG: 16:25:24.738: TreeViewModel.vala:43: Add process 18138 Parent PID: 15106
** (com.github.stsdc.monitor:18376): DEBUG: 16:25:24.738: TreeViewModel.vala:43: Add process 18247 Parent PID: 16553
** (com.github.stsdc.monitor:18376): DEBUG: 16:25:24.738: TreeViewModel.vala:43: Add process 18376 Parent PID: 15984

** (com.github.stsdc.monitor:18376): WARNING **: 16:25:27.074: GPU.vala:67: Не удалось открыть файл «/sys/class/drm/card0/device/gpu_busy_percent»: No such file or directory

** (com.github.stsdc.monitor:18376): WARNING **: 16:25:27.075: GPU.vala:67: Не удалось открыть файл «/sys/class/drm/card0/device/gpu_busy_percent»: No such file or directory

** (com.github.stsdc.monitor:18376): WARNING **: 16:25:27.075: GPU.vala:67: Не удалось открыть файл «/sys/class/drm/card0/device/mem_busy_percent»: No such file or directory
Ошибка сегментирования

**Comment by camellan** [comment] 2021-11-10 12:35
![Снимок экрана от 2021-11-10 16-34-02](https://user-images.githubusercontent.com/7396198/141114070-d0c86226-bb1c-4779-bd6d-d507934f767e.png)
![Снимок экрана от 2021-11-10 16-34-17](https://user-images.githubusercontent.com/7396198/141114072-a39bed42-deb7-4e49-84d5-b7da4e2518a4.png)

**Comment by stsdc** [comment] 2021-11-10 13:35
@camellan thanks for testing!
Check latest commit. GPU will be fixed later.

**Comment by stsdc** [comment] 2021-11-10 13:38
For GPU please open separate issue. Would be helpful if you post what GPU you are using and files inside hwmon* directory of GPU with their values.

**Comment by camellan** [comment] 2021-11-10 14:13
> @camellan thanks for testing! Check latest commit. GPU will be fixed later.
`** (com.github.stsdc.monitor:31673): CRITICAL **: 18:05:31.890: monitor_ihwmon_paths_parser_interface_real_open_file: assertion 'filename != NULL' failed
`
This error occurs if there is no label file.


This doesn't work for me.
https://github.com/stsdc/monitor/blob/e350ebb728e625dc86f1e0f24753cc88a2f86028/src/Resources/CPU.vala#L37
![Снимок экрана от 2021-11-10 18-09-06](https://user-images.githubusercontent.com/7396198/141128198-833f3506-04bd-4ba2-8802-a54cd5379b26.png)

**Comment by camellan** [comment] 2021-11-10 14:17
> For GPU please open separate issue. Would be helpful if you post what GPU you are using and files inside hwmon* directory of GPU with their values.

My GPU Nvidia GeForce GT 610. It does not create directories in hwmon.

**Comment by stsdc** [comment] 2021-11-10 15:01
@camellan check 29398331f5b1c9101cc20e5a480de13ba41111b8

**Comment by camellan** [comment] 2021-11-10 15:36
In GPU.vala ttemporarily changed otherwise it fell on the segfault:

`
public int percentage {
        get {
            // return int.parse (get_sysfs_value ("/sys/class/drm/card0/device/gpu_busy_percent"));
            return 50;
        }
    }

    public int memory_percentage {
        get {
            // return int.parse (get_sysfs_value ("/sys/class/drm/card0/device/mem_busy_percent"));
            return 50;
        }
    }

    public int memory_vram_used {
        get {
            // return int.parse (get_sysfs_value ("/sys/class/drm/card0/device/mem_info_vram_used"));
            return 50;
        }
    }

    public double temperature {
        get {
            // return int.parse (get_sysfs_value (paths_temperatures.get ("edge").input)) / 1000;
            return 50;
        }
    } `

**Comment by stsdc** [comment] 2021-11-10 18:59
@camellan made a few changes. Can You confirm it still works? :D

**Comment by camellan** [comment] 2021-11-10 19:25
> @camellan made a few changes. Can You confirm it still works? :D

All ok.

**Comment by stsdc** [comment] 2021-11-11 15:13
@camellan check `dev` branch. Should eliminate GPU errors.

**Closed** 2021-11-13 21:55 UTC
Labels: help wanted
