### ISSUE TITLE
Monitor for Juno

### ISSUE THREAD

**Issue by ndc07** [stsdc/monitor#59] opened 2018-10-18 05:28 UTC
I have used Monitor on elementary OS Loki, it is so wonderful and useful.
I just installed Juno but  I couldn't find Monitor on  App Center. When do you update it on App Center. Thank you so much!

**Comment by stsdc** [comment] 2018-10-18 14:06
Duplicate of #57

**Closed by stsdc** 2018-10-18 14:06 UTC
