### ISSUE TITLE
Indicators not showing in last update

### ISSUE THREAD

**Issue by amirhaouala** [stsdc/monitor#230] opened 2021-04-22 12:32 UTC
![image](https://user-images.githubusercontent.com/79264082/115714498-15f4e380-a36f-11eb-83ec-7f8252bfb846.png)

**Comment by amirhaouala** [comment] 2021-04-22 12:32
It just adds a bit of space

**Comment by stsdc** [comment] 2021-04-22 21:39
Duplicate of #228

**Closed by stsdc** 2021-04-22 21:39 UTC
