### ISSUE TITLE
Ascending/descending sorting of columns is reset at every launch

### ISSUE THREAD

**Issue by Slater91** [stsdc/monitor#364] opened 2023-11-12 23:08 UTC
Upon launch, Monitor shows a weird sorting which seems to be by PID, except that some processes are placed above PID 1. If I set a different sorting, e.g. by highest RAM occupation, this is then reset after every launch. It would be quite useful if the sorting was memorised by the application and used as default on subsequent launches, as I think it is a fair assumption that the user will most likely always want the same sorting.

Thanks for your efforts in developing Monitor, it's a great app!

**Comment by stsdc** [comment] 2023-11-13 23:56
Thank you for opening this issue. This issue is a duplicate of #48. Some of the work is done in #286, but not completed. I will close this issue, so we can track progress in #48.

**Closed by stsdc** 2023-11-13 23:56 UTC

**Comment by Slater91** [comment] 2023-11-14 08:49
I searched for any pre-existing issue but couldn't find any, thanks for pointing me towards #48.

**Comment by stsdc** [comment] 2023-11-14 15:34
No problem :grinning:
